/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function Timesquare(props) {
  const { nodes, materials } = useGLTF("./timesquare.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall.geometry}
        material={materials["Material.003"]}
      />
      <group
        position={[4.9, -0.24, -0.32]}
        rotation={[0, -1.57, 0]}
        scale={[0.18, 0.18, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브002.geometry}
          material={materials.Picframe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브002_1.geometry}
          material={materials["picM.004"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cam_frame.geometry}
        material={materials["Material.002"]}
      />
      <group
        position={[3.9, -0.07, -0.65]}
        rotation={[0, -1.57, 0]}
        scale={[0.54, 0.54, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브008.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브008_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.top.geometry}
        material={materials["Material.005"]}
        position={[2.02, 2.34, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials["Material.003"]}
        position={[2, 2.34, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cam_frame_1.geometry}
        material={materials["Material.002"]}
      />
      <group position={[3.97, -0.24, -1]} scale={[0.18, 0.18, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브011.geometry}
          material={materials.Picframe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브011_1.geometry}
          material={materials["picM.007"]}
        />
      </group>
      <group position={[1.14, -0.07, 0]} scale={[0.54, 0.54, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브020.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브020_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[3.65, -0.07, 0]} scale={[0.54, 0.54, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브012.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브012_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group
        position={[4.9, -0.24, 0.8]}
        rotation={[0, -1.57, 0]}
        scale={[0.18, 0.18, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브023.geometry}
          material={materials.Picframe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브023_1.geometry}
          material={materials["picM.008"]}
        />
      </group>
      <group position={[2.71, -0.24, -1]} scale={[0.18, 0.18, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브017.geometry}
          material={materials.Picframe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브017_1.geometry}
          material={materials["picM.006"]}
        />
      </group>
      <group position={[2.39, -0.07, 0]} scale={[0.54, 0.54, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브018.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브018_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[1.46, -0.24, -1]} scale={[0.18, 0.18, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브019.geometry}
          material={materials.Picframe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브019_1.geometry}
          material={materials["picM.005"]}
        />
      </group>
      <group position={[0.2, -0.24, -1]} scale={[0.18, 0.18, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브021.geometry}
          material={materials.Picframe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브021_1.geometry}
          material={materials["picM.001"]}
        />
      </group>
      <group position={[-0.12, -0.07, 0]} scale={[0.54, 0.54, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브022.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브022_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group
        position={[3.9, -0.07, 0.48]}
        rotation={[0, -1.57, 0]}
        scale={[0.54, 0.54, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브024.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.큐브024_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./timesquare.glb");